### ISSUE TITLE
problem with the importprivkey

### ISSUE THREAD

**Issue by maxihatop** [walletgeneratornet/WalletGenerator.net#48]
Emercoin customer reports problem - he generated keypair with your site, but unable 
to load private key to new wallet.
Error happening here:
    CBitcoinSecret vchSecret;
    bool fGood = vchSecret.SetString(strSecret);

 We assume, this is happening, since Bitcoin changed EC crypto library to more secure,
and code verification is more strict. Emercoin is inherited the code, and some priv keys are rejected.
We suggest customer upload key to old wallet, and on the old wallet (and old EC-lib) import has been OK.
So, I think, you needed upgrade your site, and apply last Bitcoin security patches.

See problem discussion here:
https://bitcointalk.org/index.php?topic=362513.msg16826937#msg16826937

**Comment by MichaelMure** [comment]
Hi,

Is this still a problem ?

**Comment by ghost** [comment]
I believe this is still ongoing as users are still occasionally raising an issue when importing private keys generated with Walletgenerator into the Emercoin client.

Not sure if it's related or of any help but there was a recent post on bitcointalk by someone claiming to have fixed a problem concerning Emercoin compressed keys and Walletgenerator. They were suggested to submit their fix to GitHub rather than just dumping it in the bitcointalk, but I don't think they did. The link to their post is https://bitcointalk.org/index.php?topic=362513.msg23806843#msg23806843

Though perhaps the issue is exactly as described by @maxihatop above...

**Comment by MichaelMure** [comment]
In the downloadable fork of walletgenerator, the configuration for EmerCoin is:
`janin.currency.createCurrency ("EmerCoin", 0x21, 0x80, "V", "[K,L]" , "EKGhfyN1wZyBMyV2XFUBdisC5SbKHFhq2R"),`
instead of
`janin.currency.createCurrency ("Emercoin",            0x21, 0xa1, "6",    "Q"    , "EN5nVyEbLrhYfcjoyGgQFtD3QHETyj1dy1"),`

This suggest that either the configuration was wrong since it was introduced the 17/01/2016 or Emercoin changed the address scheme for some reason (this is my guess since an old client seems to import the wallet properly).

Can someone follow [this guide](https://github.com/MichaelMure/WalletGenerator.net/wiki/How-to-add-a-new-currency) with a recent Ermercoin client to confirm it is the right fix ?

It's a bit annoying when someone does the work to fix a bug in an open source project but doesn't report the fix back, drop the result somewhere and ask for donation ...

**Comment by ghost** [comment]
Thank you for looking into this. I'm not sure exactly why emercoin would have changed address scheme - any idea from what @maxihatop has said above? In my experience all emc addresses have remained valid since the coin's launch, but that the keys generated by walletgenerator stopped importing into the emercoin client after emercoin version v0.3.7 was replaced.

Anyway, following the guide with the latest emercoin I received the following:

```janin.currency.createCurrency ("Emercoin",            0x21, 0x80, "5",    "[LK]"    , "EN5nVyEbLrhYfcjoyGgQFtD3QHETyj1dy1"),```


(note the third and fourth parameters are different from the 'fix' that was dropped on bitcointalk)

Then, using the above values in a local copy of walletgenerator I was able to confirm the successful import of multiple (~10) generated private keys (both compressed and uncompressed) into the latest emercoin client.

If this all looks good I'll proceed to make a PR with the change.

**Comment by MichaelMure** [comment]
> I'm not sure exactly why emercoin would have changed address scheme

Because that doesn't make sense ... My guess is that they switched to another code base and didn't bother to make the private key format to match the previous one. The constant `0x80` is the same as bitcoin's so it might come from here.

> In my experience all emc addresses have remained valid since the coin's launch

The public address format didn't change. The problem appears when using old private keys, ie, when importing a paper wallet.

Please make the PR :-)

**Comment by ghost** [comment]
Thanks, I have made the PR (#101), hopefully acceptable.

The emercoin devs have always been quite diligent about maintaining their code, so I am still unclear why the private key format changed. If for no other reason then I would assume that not updating the private key format when merging in fixes from the latest BTC code was an oversight rather than a case of laziness :)

Anyway thanks again and hope this will clear up the issue users were experiencing!

**Comment by ghost** [comment]
For anyone having difficulty importing a WalletGenerator EMC key into the newer versions of Emercoin and reading this...

Apparently you can use the "reencodeoldprivkey" debug command, specially added in Emercoin 0.5.x.

e.g:

```reencodeoldprivkey XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX```

It should return the same key to you, but in the format that is suitable for 0.5.x and higher. Then you use importprivkey as usual.

(I still don't know why emercoin devs changed the address format - but nice there is this conversion method built in to the client to help people who used paperwallet)

**Comment by MichaelMure** [comment]
PR merged, it will be available live with the new release or immediately when downloading an offline copy from github.

**Comment by MichaelMure** [comment]
Thank you ! :+1:
